# Site settings
title: Deerful
email: emma@deerful.com
url: http://emmawinston.me/deerful
description: "Owl & Mouse are a five-piece band from London, writing and performing bittersweet, open-hearted indiepop songs with a folk tinge."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#00588e'

# Footer settings
footer: Emma Winston

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/deer_ful
  - title: facebook
    url: https://www.facebook.com/deerful

# Build settings
markdown: kramdown
permalink: pretty
