# Site settings
title: Deerful
email: emma@deerful.com
url: https://deerful.com
description: "Music by Emma Winston, singer-songwriter, live-coder and algorithmic pixie dream girl."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#eeeeee'
  links: '#ca8ba8'

# Footer settings
footer: Emma Winston

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/deer_ful
  - title: facebook
    url: https://facebook.com/deerful
  - title: instagram
    url: https://instagram.com/deer_ful
  - title: patreon
    url: https://patreon.com/deerful
  - title: soundcloud
    url: https://soundcloud.com/deerful
  - title: youtube
    url: https://youtube.com/deerful
  - title: mastodon
    url: https://friend.camp/deerful


# Build settings
markdown: kramdown
permalink: pretty
